default_stages: [manual, commit]
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
      args: [--unsafe]
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.12.0
  hooks:
    - id: gitlint
      stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
    - id: script-must-have-extension
      types: [shell, non-executable]
    - id: shellcheck
      args: [-a, -x]
    - id: shfmt
- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.0
  hooks:
    - id: markdown-toc
    - id: dockerfile_lint
      args: [--verbose]
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: circleci-config-validate
