default_stages: [manual, commit]
fail_fast: false
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
    - id: check-added-large-files
    - id: check-ast
    - id: check-case-conflict
    - id: check-executables-have-shebangs
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: check-toml
    - id: check-xml
    - id: check-yaml
    - id: detect-private-key
    - id: end-of-file-fixer
    - id: fix-encoding-pragma
    - id: mixed-line-ending
    - id: requirements-txt-fixer
    - id: sort-simple-yaml
    - id: trailing-whitespace
      args: [--markdown-linebreak-ext=md]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.12.0
  hooks:
    - id: gitlint
      stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 1.11.0
  hooks:
    - id: script-must-have-extension
      types: [shell, non-executable]
    - id: shellcheck
      args: [--color=always, -a, -x]
      additional_dependencies: [shellcheck]
    - id: shfmt
      additional_dependencies: [shfmt]
- repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
  rev: v1.1.0
  hooks:
    - id: markdown-toc
    - id: dockerfile_lint
      args: [--verbose]
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: circleci-config-validate
- repo: https://github.com/cheshirekow/cmake-format-precommit
  rev: v0.6.2
  hooks:
    - id: cmake-format
      types: [cmake]
      args: [-i]
- repo: https://github.com/codespell-project/codespell.git
  rev: v1.16.0
  hooks:
    - id: codespell
      args: ['-L', 'ot']
- repo: https://github.com/zbeekman/pre-commit-hooks
  rev: zbeekman-macOS-patch
  hooks:
    - id: clang-tidy
      args: [--header-filter=.*, --fix, --fix-errors]
    - id: oclint
      args: [-enable-clang-static-analyzer, -enable-global-analysis]
- repo: git://github.com/doublify/pre-commit-clang-format
  rev: master
  hooks:
    - id: clang-format
      args: [-style=file,-fallback-style=none,-i]
      files: \.(c|cc|cxx|cpp|h|hpp|hxx)$
