ignore:
  - "**/GNU/testing.F*"
  - "**/extern/**"

codecov:
  require_ci_to_pass: yes
  branch: develop

coverage:
  precision: 2
  round: nearest
  range: "60...98"
  status:
    project:
      default:
        target: 90%
      unittest_core:
        flags: unittest_core
        target: 95%
        paths:
          - "!*/test/*"
          - "!*/extern/*"
          - "!*_test.[Ff]90"
          - "!*_test.c"
          - "!*/GNU/testing.F90"
          - "*/generated/GNU/*.[Ff]90"
          - "*/src/*.[Ff]90"
          - "*/src/*.c"
          - "*/src/c_interfaces/*.c"
      unittest_tests:
        flags: unittest_tests
        target: auto
        threshold: 2
        paths:
          - "*/test/*.[Ff]90"
          - "*/test/*.c"
          - "*_test.[Ff]90"
          - "*_test.c"
          - "*/generated/GNU/test/*.[Ff]90"
          - "*/src/test/*.[Ff]90"
          - "*/src/test/*.c"
    patch:
      default:
        target: 55%
      unittest_core:
        flags: unittest_core
        target: 60%
        paths:
          - "!*/test/*"
          - "!*/extern/*"
          - "!*_test.[Ff]90"
          - "!*_test.c"
          - "!*/GNU/testing.F90"
          - "*/generated/GNU/*.[Ff]90"
          - "*/src/*.[Ff]90"
          - "*/src/*.c"
          - "*/src/c_interfaces/*.c"
      unittest_tests:
        flags: unittest_tests
        target: auto
        threshold: 2
        paths:
          - "*/test/*.[Ff]90"
          - "*/test/*.c"
          - "*_test.[Ff]90"
          - "*_test.c"
          - "*/generated/GNU/test/*.[Ff]90"
          - "*/src/test/*.[Ff]90"
          - "*/src/test/*.c"

    # changes:
    #   default: off
    #   unittest_core: *unit_core
    #   unittest_tests: *unit_tests

flags:
  # filter the folder(s) you wish to measure by that flag
  unittest_core:
    paths:
      - "!*/test/*"
      - "!*/extern/*"
      - "!*_test.[Ff]90"
      - "!*_test.c"
      - "!*/GNU/testing.F90"
      - "*/generated/GNU/*.[Ff]90"
      - "*/src/*.[Ff]90"
      - "*/src/*.c"
      - "*/src/c_interfaces/*.c"
  unittest_tests:
    paths:
      - "*/test/*.[Ff]90"
      - "*/test/*.c"
      - "*_test.[Ff]90"
      - "*_test.c"
      - "*/generated/GNU/test/*.[Ff]90"
      - "*/src/test/*.[Ff]90"
      - "*/src/test/*.c"

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  branches: [master, develop]
