name: misspell
on: [pull_request]
jobs:
  misspell:
    name: misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: misspell
        uses: reviewdog/action-misspell@v1
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.reviewdog_token }}
        with:
          github_token: ${{ secrets.reviewdog_token }}
          locale: "US"
          reporter: github-pr-review
